
SHELL := /bin/bash

all:
	gcc -g -I../../../include src/time_test_main.c src/game_engine/*.c ../../../src/server/networking/*.c ../../../src/server/game_engine/*.c -o bin/basic_test_bin

test : 
	ls -al
